### ISSUE TITLE
Basic: Filter (Exercise 4)

### ISSUE THREAD

**Issue by tynar** [timoxley/functional-javascript-workshop#104]
Hello,

I've been learning node.js and end up with an answer like below:
//4.js
function getShortMessages(messages) {
    return messages.filter(function (val){
        return val.message.length < 50;
    });
}

module.exports = getShortMessages

But this answer cannot pass the verification, although if I test my answer like this:
//4_test.js
var getShortMessages = require('./4.js');

var messages = [ { message: 'Anim tempor irure cupidatat sint culpa laborum.' }, { message: 'Aliqua nostrud irure ut dolore sint minim id.' } ];

console.log(getShortMessages(messages));
//results

[ { message: 'Anim tempor irure cupidatat sint culpa laborum.' },
  { message: 'Aliqua nostrud irure ut dolore sint minim id.' } ]

The result seems to be correct, though! Am I doing something wrong?

**Comment by henns20** [comment]
You missing a part of the required task.

The input is an array of objs with message properties, and
the output 'returns an array of messages that are less than 50 chars long'. You currently have an array of objs still with message properties.  It 'hints' in the exercise: Try chaining some Array methods!

So output should look like this.
[ 'Et sit id duis voluptate irure dolor est ex.', 'Mollit anim sunt sunt ex in.', 'Minim minim dolore non qui.', 'In aliqua aute amet et dolor exercitation.' ]

You  need to use map function to complete.
If you get stuck with an exercise and just can't figure it out- you can access the solution on the github project page. 
https://github.com/timoxley/functional-javascript-workshop/tree/master/exercises
For this one for example, 
https://github.com/timoxley/functional-javascript-workshop/tree/master/exercises/basic_filter/solution

Cheers

**Comment by sajt** [comment]
This is what I do not understand. Why changed the object to string?
