### ISSUE TITLE
Function Spies

### ISSUE THREAD

**Issue by botteu** [timoxley/functional-javascript-workshop#105]
I was doing the Function spies workshop and almost made it ;) Although I had to look at the solution in the end to understand what was happening.

One thing I don't get though is why the replacement function has to return anything. Since the replacement function replaces the original function, shouldn't it be enough to just invoke the original function with apply?

 target[method] = function() {
        result.count++ // track function was called
        return originalFunction.apply(this, arguments) // invoke original function
 }

So if target[method] is console.log for example then:

 console.log = function() {
        result.count++ // track function was called
        return originalFunction.apply(this, arguments) // invoke original function
 }

But console.log doesn't return anything, it just writes to the console. So why does the replacement function return the result of originalFunction.apply(this, arguments)?

**Comment by thirtified** [comment]
Well, you want the spy to be able to replace all sorts of functions, right? That is, it should also work functions that do have a return value. You are right, for `console.log` the handling of the return value is not necessary, as this original function itself does not return anything. But in general, as mentioned in the excercise's hint,
 > Functions have context, input and output.
For general applicability you therefore need to handle funcion outputs.

**Comment by botteu** [comment]
Ah, now I see.

Thank you :)

**Comment by timoxley** [comment]
:D

**Comment by gs20060101** [comment]
I was trapped in the same hole and just executed the target method without returning its returning value. The verifier produced error message "✗ Check your function's return value!" but it still gave my code "pass".
