### ISSUE TITLE
[Request] Recursion: solution without add additional arguments

### ISSUE THREAD

**Issue by CNBorn** [timoxley/functional-javascript-workshop#114]
As the description point out:

    // Note: Feel free to add additional arguments
    // to this function for use with recursive calls.
    // Or not! There are many ways to recurse.

Is there any solutions without adding additional arguments? I think it would be a good thing to add to solutions.

**Comment by timoxley** [comment]
> Is there any solutions without adding additional arguments? 

One solution is to use an inner/helper function to do the actual recursion, and define the results/tracking information in the outer function, something like this:

```js
function outer(count) {
  var items = []
  function inner(innerCount) {
    if (innerCount === 0) return items 
    items.push(innerCount)
    inner(--innerCount)
  }
  inner(count)
  return items
}
```
But yeah it would be good to offer alternative solutions.

**Comment by timoxley** [comment]
Closing, feel free to reopen if you have further questions!
