### ISSUE TITLE
Basic recursions uses helper function

### ISSUE THREAD

**Issue by melearning** [timoxley/functional-javascript-workshop#115]
One of the conditions of the task is to not use any "unnecessary", functions, e.g. helper functions.

I finally gave up and used a helper function, and I see that the official solution uses a helper function.

**Comment by awong650** [comment]
function reduce(arr, fn, initial) {
	var obj = initial;
	if (!arr.length) return obj;
	var head = arr[0];
	var index = 1;
	obj = fn(obj, head, index, arr);
	return reduce(arr.slice(1), fn, obj);
}

module.exports = reduce;

No helper function needed.

**Comment by timoxley** [comment]
Agreed this was confusing. I've fixed this now.
