### ISSUE TITLE
Submission: undefined

### ISSUE THREAD

**Issue by be-codified** [timoxley/functional-javascript-workshop#120]
My input:

    function upperCaser(input) {
        input.toUpperCase()
    }

    module.exports = upperCaser

My output 1:

    functional-javascript run program.js

    input: 'Quis ipsum consequat laboris ex nostrud dolor in ullamco elit labore sunt ad.'
    submission: undefined

My output 2

    functional-javascript verify program.js

    input: 'Quis dolore pariatur eu elit excepteur mollit ipsum incididunt.'
    submission: undefined
    solution: 'QUIS DOLORE PARIATUR EU ELIT EXCEPTEUR MOLLIT IPSUM INCIDIDUNT.'

    # FAIL

    Your solution to Hello World didn't pass. Try again!

What am I doing wrong?

**Comment by Ryan1729** [comment]
You didn't return anything from the function.

**Comment by be-codified** [comment]
Ah, I see. Thank you.
