### ISSUE TITLE
Basic call - superfluous slice()

### ISSUE THREAD

**Issue by superclarkk** [timoxley/functional-javascript-workshop#123]
Forgive me if I'm wrong, but the slice() method seems superfluous in the solution to exercise 8. If it's not, then `verify` should fail when it is not used (ie a value should be passed that makes the following code fail):

~~~
function duckCount() {
	return Array.prototype.filter.call(arguments, function(arg){
		return Object.prototype.hasOwnProperty.call(arg, 'quack'); 
	}).length;
}

module.exports = duckCount;
~~~

**Comment by timoxley** [comment]
See https://github.com/nodeschool/discussions/issues/231#issuecomment-38826949
