### ISSUE TITLE
Why the missing semicolons

### ISSUE THREAD

**Issue by jtwebman** [timoxley/functional-javascript-workshop#130]
I understand in Javascript they are not required 95% of the time but it is much easier to read and reason with them in there. Also it is far easier for new programmers to understand to put them in vs having to know the few times they have to add them. Would you guys except a pull request with them add in?

**Comment by timoxley** [comment]
>  it is much easier to read and reason with them in there

This depends which other language's baggage you're carrying into JS. If your other language doesn't require semicolons e.g. python, ruby, scala, then semicolons are just noise.


> Also it is far easier for new programmers to understand to put them in vs having to know the few times they have to add them.

You really only need to add them in 3 cases: loop constructs, lines starting with `[` and lines starting with `(`. 

> Would you guys except a pull request with them add in?

No thank you.
