### ISSUE TITLE
menu does not allow arrow up and arrow down to select next exercise

### ISSUE THREAD

**Issue by cpoptic** [timoxley/functional-javascript-workshop#135]
This is probably related to the exact same bug in learnyounode & workshopper, since this appears to be built on the workshopper framework.  I can complete the first exercise (hello_world), but upon returning to the menu to select subsequent exercises, I am unable to scroll down to choose the next one.  

I am running this on Windows 8.1 OS with x64 architecture.

The responses on the learnyounode issues forum suggest this is a bug related to the most recent version of javascript not playing nicely with Windows 8/8.1.

As it stands, this workshop is limited to a one-exercise workshop.

**Comment by timoxley** [comment]
Related:

https://github.com/workshopper/workshopper/issues/120
https://github.com/workshopper/learnyounode/issues/355

Workaround is to run `functional-javascript next` to move to the next lesson or `functional-javascript select n` to move to exercise `n`.

**Comment by SomeoneWeird** [comment]
This has been fixed upstream in node 5.1.0

**Comment by cpoptic** [comment]
I have updated to node 5.1.0 and can confirm that this has indeed solved the issue.
