### ISSUE TITLE
async loop solution does not pass

### ISSUE THREAD

**Issue by connor11528** [timoxley/functional-javascript-workshop#63]
I use your solution code for async-loops but still does not pass. The exercise (run or verify) haaaangs.

code:

```
function loadUsers(userIds, load, done) {
  var completed = 0
  var users = []
  userIds.forEach(function(id, index) {
    load(id, function(user) {
      console.log(user) // logs out one or two user objects
      users[index] = user
      if (++completed === userIds.length) return done(users)
    })
  })
}

module.exports = loadUsers
```

not passing for me

**Comment by igorbelykh86** [comment]
Hello,
I've solved this problem by following way:

    function loadUsers(userIds, load, done) {
        var users = {length: 0};
        userIds.forEach(function(val, index) {
            load(val, function(data) {
                users[index] = data;
                if(++users.length == userIds.length) done(Array.prototype.slice.call(users, 0));
            });
        });
    }

Why this solution is worse?
