### ISSUE TITLE
Excersize [1]: (num, operation) would make more sense

### ISSUE THREAD

**Issue by gramergrater** [timoxley/functional-javascript-workshop#73]
If you're using FP and composing functions out of other functions, you're constantly modifying the behaviour of existing functions. A curried repeat would be useful in FP, e.g.:
```javascript
var twice = repeat(2)
```
Now we can make anything happen twice, e.g.:
```javascript
var doubleclick = twice(click)

doubleclick(thatButton)
```
Just my $.02

**Comment by timoxley** [comment]
Great point but not all that important for this example code. Thanks!
