### ISSUE TITLE
Exercise [1] - Pass with wrong solution

### ISSUE THREAD

**Issue by guilhermeleobas** [timoxley/functional-javascript-workshop#77]
I think I found a bug in the judge for exercise [1].

See the image below:
http://i.imgur.com/thHYzV0.png

```javascript
function repeat (operation, num){
  
  if (num == null){
    return;
  }

  if (num > 0){
    operation ();
    num -= 1;
//    repeat (operation, num);
  }
}

module.exports = repeat;
```

If the judge calls repeat with num equals to 1, I got accepted. I think the purpose of the exercise involves a little bit of recursion and would be better if the judge only run tests with num equals to 2 or greater.

**Comment by timoxley** [comment]
I believe this is fixed now, [minimum is 3](https://github.com/timoxley/functional-javascript-workshop/blob/b1de955396d48c65962d1a5b7423658e280c9e05/exercises/higher_order_functions/exercise.js#L13)
