### ISSUE TITLE
Recursion Dependency Order

### ISSUE THREAD

**Issue by covlllp** [timoxley/functional-javascript-workshop#80]
Unless I'm doing it wrong, I seem to get getting the correct answer for the Recursion problem, but my dependencies and versions are listed in a different order than what the solution is expecting. My code is below:

```javascript
function getDependencies(tree) {
	var arr = [];

	function _addDependencies(tree) {
		// check if there are dependencies
		if (!(tree.hasOwnProperty('dependencies'))) return;

		Object.keys(tree.dependencies).reverse().forEach(function(dep) {
			_addDependencies(tree.dependencies[dep]);
			var id = dep + "@" + tree.dependencies[dep].version;
			if (arr.indexOf(id) === -1) arr.push(id);
		});
	}

	_addDependencies(tree);
	return arr;
}

module.exports = getDependencies;
```

Am I approaching this problem incorrectly, or is this a bug?

**Comment by timoxley** [comment]
> Implement a recursive function that returns all of the unique dependencies, and sub-dependencies of a module, sorted alphabetically

> sorted alphabetically

I don't see any sorting in your solution!

**Comment by covlllp** [comment]
oh shoot, I guess I read through the prompt too quickly! Thanks!

**Comment by timoxley** [comment]
:+1:

**Comment by swinston100** [comment]
@covlllp - 


I found your solution caused an error

> TypeError: Cannot read property 'hasOwnProperty' of undefined
>     at _addDependencies (C:\Users\steven\functionalJS\fjsex16.js:13:16)


Perhaps consider:

`js
  if (**tree === undefined** || !(tree.hasOwnProperty('dependencies'))) return;
`
?
Thanks for your solution and chat above, it helped me a lot.
