### ISSUE TITLE
Exercise [10] - First argument in #bind

### ISSUE THREAD

**Issue by mrmaka** [timoxley/functional-javascript-workshop#91]
I am confused about first argument `console` in official solution:
```javascript
module.exports = function(namespace){
  return console.log.bind(console, namespace);
}
```
My solution:
```javascript
module.exports = function (namespace){
  return console.log.bind(null, namespace);
}
```

What the difference between `console` and `null` in this case?

**Comment by timoxley** [comment]
Try the second one in the browser. Browser `console.log` wants `this` to be `console`.

**Comment by timoxley** [comment]
In node, there's no effective difference.

**Comment by mrmaka** [comment]
It is veryVeryVery helpful workshop, thank you veryVeryVery much!)

**Comment by timoxley** [comment]
Please reopen if you have any further questions.
