### ISSUE TITLE
Translations needed

### ISSUE THREAD

**Issue by timoxley** [timoxley/functional-javascript-workshop#93]
Some recent changes need translations, I did some google translating but can you have a look at the commits below please @tdd?

**Comment by timoxley** [comment]
Also how can we get the translation API happening in the wrapper files so it's not all inline?

**Comment by tdd** [comment]
Hey @timoxley! Just pushed a quick set of FR L10n tweaks. Beware of Google translate :wink: 

The wrapper system here is specific to your repo, not what we usually go with for `workshopper`. I'll have to dive into this deeper in the future to try and find a clean way to do this right from the infra. `workshopper-wrappedexec` is something different still (mostly used to hook into various API method calls so we can trace them and assert they're used / not used).

I don't see an easy way to let wrappers, which are plain Node programs, access workshopper's i18n layer right now (which is far more complex than it seems at first glance). I agree inline translation stinks, with its duplicated wrapper files, but that's as good as we can get just now :disappointed:

**Comment by timoxley** [comment]
> Just pushed a quick set of FR L10n tweaks

Thank you! :dancer: 

> Beware of Google translate :wink:

Yeah I knew it was going to be crappy, but perhaps better than nothing until you got a chance to rework it.
