### ISSUE TITLE
Collision of question and solution in 'Implement map with reduce'

### ISSUE THREAD

**Issue by robinpokorny** [timoxley/functional-javascript-workshop#96]
Current task for **[Implement map with reduce](https://github.com/timoxley/functional-javascript-workshop/blob/master/exercises/implement_map_with_reduce/problem.md)** is to write “a simple version of Array#map”. That corresponds with provided boilerplate.

However, the [official solution](https://github.com/timoxley/functional-javascript-workshop/blob/master/exercises/implement_map_with_reduce/solution/solution.js) implements even the second argument. This could be confusing.

I propose to keep the simple version.

This matter was discussed and fixed in [#35](https://github.com/timoxley/functional-javascript-workshop/issues/35). It was, unfortunately, introduced again in [#81](https://github.com/timoxley/functional-javascript-workshop/pull/81).

**Comment by PWAckerman** [comment]
To put another way, the boilerplate in the problem is misleading, as the official solution differs considerably in both the name of the function(Boilerplate: name is "arrayMap", solution: name is just "map") and the number of arguments (2 in the boilerplate, 3 in the solution).

**Comment by robinpokorny** [comment]
Yes, you could put it that way. I still find the task and boilerplate the genuine part and propose to edit the solution.

**Comment by timoxley** [comment]
Ideally, we could split it into two tasks.  One to implement the simple version, second to implement the `thisArg` handling.

**Comment by robinpokorny** [comment]
@timoxley That is a good idea. And I think it would be a nice learning experience as well.
