### ISSUE TITLE
Trampoline

### ISSUE THREAD

**Issue by Djabx** [timoxley/functional-javascript-workshop#98]
Hy,

First: thank you for this good tuto.
I was doing the 14th question and answer with this:
https://github.com/Djabx/tuto_functionnal-js/blob/master/14.js

Your solution is this:
https://github.com/Djabx/tuto_functionnal-js/blob/master/14.js

Obviously I missed the trick.

What was not said nor that I understand it, was the "RangeError" does not seems to be an exception that interrupt the process; it's just return do not call the function, so we can grab the result and just recall it.

Tell me if I'm wrong, or if I miss something, but I think you should explain that in the "hints" section.

Tks.

**Comment by RichardIvan** [comment]
Exactly, I'd really want some sort of description behind why the code works the way it does.
